### PR TITLE
Comment on line 1 if no line set

### PR DESCRIPTION
**Pull request by guykisel**
@raphaelcastaneda

### CODE REVIEW

**Comment by raphaelcastaneda** [comment]
I guess I should have commented on the PR and not in slack.

> so in your case, if your line is 0, where do you post the message?
this might "accidentally" work in stash, because if you use the API to post to a line number that either doesn't exist, or is not adjacent to the diff, it ends up being a file comment

**Comment by raphaelcastaneda** [comment]
I liked it better when this would make stash/bitbucket post a file comment. Github doesn't seem to have that feature, but I wonder if there's good way to get that behavior back.

**Comment by guykisel** [comment]
maybe this could instead just leave the line number as null/zero, then let the interface handle it?

**Comment by raphaelcastaneda** [comment]
that works for me

**Pull request closed without merging**
